### ISSUE TITLE
Automate upload functionality

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/ui#91]
- [x] Add a one- or two-liner on "Upload" page with instructions: upload data dictionary (JSON), include dataset ID for ON dataset (not name), etc.
- [x] Turn Upload page into a simple form with:
  - [x] dataset id
  - [x] upload JSON file, and show file name
  - [x] Github details:
    - [x] User name (required)
    - [x] User email (required)
    - [x] GitHub username
    - [x] Get rid of "pull request title" - we'll automate
    - [x] Pull request description -> Summary of changes to data dictionary
      - [x] if possible, add a brief example ("Added annotation for age and sex columns")
- [x] Move submit button to bottom
- [x] Once successfully submitted, display text to user with PR link + some context for what happens next, how to add more info

**Comment by alyssadai** [comment]
@surchs, here's the spec Arman and I wrote for what the UI should look like for the JSON upload functionality for OpenNeuro. Note that the user will no longer be logging in through GH for now. Let us know if you have any additional thoughts. The sister issue in the uploader API is specced [here](https://github.com/neurobagel/tools/issues/24)

**Comment by alyssadai** [comment]
Hey @rmanaem,

Following up on what we can include as user instructions for the upload page, here's a suggestion:

> **Instructions:**
> 
> Use this page to contribute a Neurobagel annotation for an existing (OpenNeuro dataset)[link to our org? website?]. 
> 
> 1. Upload a JSON data dictionary that has been [annotated using Neurobagel](link to annotation tool) for validation, and provide your contact details so we can verify the legitimacy of the submission.
> 2. If your upload is successful, a pull request will automatically be opened in the GitHub repository corresponding to the OpenNeuro dataset.

I'd recommend displaying this in full in text (rather than something you need to expand) since I think it provides important context before the user submits anything. Lmkwyt!

**Comment by rmanaem** [comment]
> I'd recommend displaying this in full in text (rather than something you need to expand) since I think it provides important context before the user submits anything. Lmkwyt!

@alyssadai Sounds good
Could you post an example of a curl request here?

**Comment by alyssadai** [comment]
Yes, here you go:

```bash
curl -X 'PUT' \
  'http://localhost:8000/openneuro/upload?dataset_id=ds005028' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'data_dictionary=@participants_test2.json;type=application/json' \
  -F 'changes_summary=added age annotation' \
  -F 'name=Alyssa' \
  -F 'email=bob.thebuilder@gmail.com' \
```
`dataset_id` is still a query parameter, but everything else is a form field. `data_dictionary` expects a path to a file.
In this example, the optional fields `affiliation` and `gh_username` are left empty (excluded).

Also of note, `changes_summary` can handle newline characters, in case the summary of changes provided by the user spans multiple lines.

I think you already added this, but I'd recommend prompting the user to be specific in the changes summary, e.g. "Added age and sex annotation" instead of just "updated participants.json".

Finally, if there is an easy way to indicate in the UI field that the GitHub username should not be prefixed with an "@" (since we add this in the API when constructing the PR body), that would be cool. I have a `#TODO` in the API to add some validation of the username to strip leading "@" for this reason, but for now, I think a visual indication or example is sufficient

**Comment by alyssadai** [comment]
See https://github.com/neurobagel/tools/pull/26 for more info

Also, see https://github.com/neurobagel/tools/blob/d905d4ce25414a52f346a0aa9449ab9774fdb6a2/app/api/models.py#L17-L34 for changes to the API response models! The PR link is now included for `SuccessfulUpload` and `SuccessfulUploadWithWarnings`
